### ISSUE TITLE
Argument 1 passed to Twig_Filter::__construct() must be of the type string, object given

### ISSUE THREAD

**Issue by randohinn** [ry167/twig-gravatar#5]
When running `    $twig->addExtension(new TwigGravatar());`, this error occurs. 

Full printout: 

> Fatal error: Uncaught TypeError: Argument 1 passed to Twig_Filter::__construct() must be of the type string, object given, called in E:\Webdev\g3\app\vendor\ry167\twig-gravatar\src\TwigGravatar.php on line 23 and defined in E:\Webdev\g3\app\vendor\twig\twig\lib\Twig\Filter.php:35 Stack trace: #0 E:\Webdev\g3\app\vendor\ry167\twig-gravatar\src\TwigGravatar.php(23): Twig_Filter->__construct(Object(TwigGravatar), 'avatar', Array) #1 E:\Webdev\g3\app\vendor\twig\twig\lib\Twig\ExtensionSet.php(429): TwigGravatar->getFilters() #2 E:\Webdev\g3\app\vendor\twig\twig\lib\Twig\ExtensionSet.php(419): Twig_ExtensionSet->initExtension(Object(TwigGravatar)) #3 E:\Webdev\g3\app\vendor\twig\twig\lib\Twig\ExtensionSet.php(388): Twig_ExtensionSet->initExtensions() #4 E:\Webdev\g3\app\vendor\twig\twig\lib\Twig\Environment.php(918): Twig_ExtensionSet->getUnaryOperators() #5 E:\Webdev\g3\app\vendor\twig\twig\lib\Twig\Lexer.php(353): Twig_Environment->getUnaryOperators() #6 E:\Webdev\g3\app\vendor\twig\twig\lib\Twig\Lexer.php(65): Twig_Lexer->g in E:\Webdev\g3\app\vendor\twig\twig\lib\Twig\Filter.php on line 35

Using Twig `~2.0`

**Comment by ryanhalliday** [comment]
Hi Rando,

Thanks for your issue report & pull request, I just have a few questions first.

`getFilters` used to return strings but was changed in #4  by someone else.
I am currently not using Twig which makes it hard for me to stay updated with what is changing so I took the previous contributors advice.

[Currently in the documentation](http://twig.sensiolabs.org/doc/2.x/advanced.html#id3) it claims to expect an array of Twig Filters without string indexes. 
Can you help me understand what could be going on here?

**Comment by randohinn** [comment]
I'm as baffled as you, This and #4 both seem to work, yet what's on composer, doesnt? May it just be an update to the version there, that hasn't been made? Because that sure breaks - the array on Composer is 
```php
return array(
			$this->filterPrefix.'Avatar'  => new \Twig_SimpleFilter($this,'avatar', $this->filterOptions),
			$this->filterPrefix.'Https'   => new \Twig_SimpleFilter($this,'https', $this->filterOptions),
			$this->filterPrefix.'Size'    => new \Twig_SimpleFilter($this,'size', $this->filterOptions),
			$this->filterPrefix.'Default' => new \Twig_SimpleFilter($this, 'def', $this->filterOptions),
			$this->filterPrefix.'Rating'  => new \Twig_SimpleFilter($this, 'rating', $this->filterOptions),
		);
```
all the `$this` in the constructors are the error here...

**Comment by ryanhalliday** [comment]
I have tagged a new release, so could you update your version in `composer.json` to `2.0.0` and run `composer update`
Let me know if that fixes the issue

**Comment by randohinn** [comment]
@ry167 Yup, that works.
